
CREATE TABLE IF NOT EXISTS TB_EMPRESA(
ID INT AUTO_INCREMENT PRIMARY KEY
, NOME_EMPRESA VARCHAR(100)	
);

CREATE TABLE IF NOT EXISTS TB_PAPEL(
ID INT AUTO_INCREMENT PRIMARY KEY
, ID_EMPRESA INT
, COD_PAPEL VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS TB_APLICACAO(
ID INT AUTO_INCREMENT PRIMARY KEY
,DATA_OPERACAO DATE
,ID_TIPO_APLICACAO INT
,ID_PAPEL INT
,ID_TIPO_OPERACAO INT
,QTD INT
,VALOR_UNITARIO FLOAT);

CREATE INDEX IF NOT EXISTS ID_TIPO_APLICACAO ON TB_APLICACAO(ID_TIPO_APLICACAO);

CREATE INDEX IF NOT EXISTS ID_PAPEL ON TB_APLICACAO(ID_PAPEL);

CREATE INDEX IF NOT EXISTS ID_TIPO_OPERACAO ON TB_APLICACAO(ID_TIPO_OPERACAO);
